// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PubProjectApi.Models;

namespace PubProjectApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20181122120154_addAdvert")]
    partial class addAdvert
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PubProjectApi.Models.Advertisement", b =>
                {
                    b.Property<Guid>("AdvertisementId")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Active");

                    b.Property<string>("Category");

                    b.Property<DateTime>("DateAdded");

                    b.Property<string>("Description");

                    b.Property<Guid>("GastronomicVenueId");

                    b.Property<string>("Tag");

                    b.Property<string>("Title");

                    b.HasKey("AdvertisementId");

                    b.HasIndex("GastronomicVenueId");

                    b.ToTable("Advertisements");
                });

            modelBuilder.Entity("PubProjectApi.Models.GastronomicVenue", b =>
                {
                    b.Property<Guid>("GastronomicVenueId")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Active");

                    b.Property<string>("City");

                    b.Property<string>("GastronomicVenueDescription");

                    b.Property<string>("GastronomicVenueName");

                    b.Property<int?>("HouseNr");

                    b.Property<double>("Latitude");

                    b.Property<int?>("LocalNr");

                    b.Property<double>("Longitude");

                    b.Property<string>("Phone");

                    b.Property<string>("PostCode");

                    b.Property<string>("Street");

                    b.Property<string>("Type");

                    b.HasKey("GastronomicVenueId");

                    b.ToTable("GastronomicVenues");
                });

            modelBuilder.Entity("PubProjectApi.Models.Advertisement", b =>
                {
                    b.HasOne("PubProjectApi.Models.GastronomicVenue", "GastronomicVenue")
                        .WithMany()
                        .HasForeignKey("GastronomicVenueId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
